#!/usr/bin/env python
import os, glob

tests = glob.glob('*')

def build():
    for test in tests:
        if not test.startswith('_'):
            if os.path.isdir(test):
                os.system('cd %s; ./bake clean; ./bake; cd ..' % test)

def gold():
    for test in tests:
        if not test.startswith('_'):
            if os.path.isdir(test):
                os.system('cd %s; ./bake gold; cd ..' % test)


build()
#gold()
