#!/usr/bin/env python
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, run

BUILD = 'build'
GOLD = 'gold'

tests = glob.glob('*.py')

def build():
    for test in tests:
        if test[0] != '_':
            base, suffix = test.split('.')
            compile(base)

def compile(base):
    u = base+'.pcf'
    v = base+'.v'
    buildu, goldu = join(BUILD,u), join(GOLD,u)
    buildv, goldv = join(BUILD,v), join(GOLD,v)
    run('python3',base+'.py', join(BUILD,base))
    if exists(goldu):
        run('cmp',buildu,goldu)
    if exists(goldv):
        run('cmp',buildv,goldv)

def clean():
    autoclean()

def gold():
    os.system('cp %s/*.v %s' % (BUILD, GOLD))
    os.system('cp %s/*.pcf %s' % (BUILD, GOLD))

main()
