#!/usr/bin/env python
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, run

target = os.getenv('MANTLE_TARGET', 'spartan3')

BUILD = 'build'
GOLD = 'gold3' if target == 'spartan3' else 'gold6'

tests = glob.glob('*.py')

def build():
    for test in tests:
        base, suffix = test.split('.')
        compile(base)

def compile(base):
    u = base+'.ucf'
    v = base+'.v'
    buildu, goldu = join(BUILD,u), join(GOLD,u)
    buildv, goldv = join(BUILD,v), join(GOLD,v)
    run('python3',base+'.py', join(BUILD,base))
    if exists(goldu):
        run('cmp',buildu,goldu)
    if exists(goldv):
        run('cmp',buildv,goldv)

def clean():
    autoclean()

def gold():
    os.system('cp %s/* %s' % (BUILD, GOLD))

main()
